// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using React_Blog.Data;

#nullable disable

namespace React_Blog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623120000_AddImageDisplayMode")]
    partial class AddImageDisplayMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");
#pragma warning restore 612, 618
        }
    }
}
