// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using React_Blog.Data;

#nullable disable

namespace React_Blog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613140000_AddVisualLayout")]
    partial class AddVisualLayout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("React_Blog.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("React_Blog.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("React_Blog.Entities.Image", b =>
                {
                    b.HasOne("React_Blog.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("React_Blog.Entities.Post", b =>
                {
                    b.OwnsOne("React_Blog.Entities.VisualLayout", "VisualLayout", b1 =>
                        {
                            b1.Property<int>("PostId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.ToJson("VisualLayout");

                            b1.OwnsMany("React_Blog.Entities.ImagePlacement", "Placements", b2 =>
                                {
                                    b2.Property<int>("VisualLayoutPostId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("AspectRatio")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("Caption")
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("CaptionEnabled")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("ImageId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("Left")
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Top")
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Width")
                                        .HasColumnType("REAL");

                                    b2.Property<int>("ZIndex")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("VisualLayoutPostId", "__synthesizedOrdinal");

                                    b2.ToTable("Posts");
                                });

                            b1.Navigation("Placements");
                        });

                    b.OwnsOne("React_Blog.Entities.VisualStyle", "VisualStyle", b1 =>
                        {
                            b1.Property<int>("PostId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BackgroundColor")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("BackgroundImageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FontSize")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.ToJson("VisualStyle");
                        });

                    b.Navigation("VisualLayout");

                    b.Navigation("VisualStyle");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
